/**
 * Emit Mihomo Party override.js
 * @param {object} ir
 * @returns {string}
 */
export function emitParty(ir) {
  const groups = ir.groups.map((g) => {
    const out = { name: g.name, type: g.type };
    if (g.proxies) out.proxies = g.proxies;
    if (g['include-all']) out['include-all'] = true;
    if (g.filter) out.filter = g.filter;
    if (g.type !== 'select') {
      if (g.url) out.url = g.url;
      if (g.interval != null) out.interval = g.interval;
      if (g.tolerance != null) out.tolerance = g.tolerance;
      out['max-failed-times'] = 3;
    }
    return out;
  });

  const exclude = ir.excludeRemarks || '';
  const bareExclude = exclude.replace(/^\(\?i\)/, '');
  const sortProxies = ir.sortProxies !== false;
  const sortLocale = ir.sortProxiesLocale || 'zh-CN';

  const general = ir.general || {};
  const generalLines = Object.entries(general)
    .map(([k, v]) => `    config[${JSON.stringify(k)}] = ${JSON.stringify(v)};`)
    .join('\n');

  const dnsBlock =
    ir.dns && typeof ir.dns === 'object'
      ? `    config.dns = ${JSON.stringify(ir.dns, null, 4).split('\n').join('\n    ')};`
      : '    // dns: left unchanged';

  const sortBlock = sortProxies
    ? `
    // Sort nodes by name (locale=${sortLocale}, numeric) so include-all groups stay stable
    const sortLocale = ${JSON.stringify(sortLocale)};
    const byName = (a, b) =>
        String(a?.name ?? a ?? '').localeCompare(String(b?.name ?? b ?? ''), sortLocale, {
            numeric: true,
            sensitivity: 'base',
        });
    if (Array.isArray(config.proxies)) {
        config.proxies = config.proxies.slice().sort(byName);
    }
`
    : `
    // sort_proxies disabled
`;

  return `/**
 * override.js — Mihomo Party (auto-generated by acl4ssr-override)
 * upstream: ${ir.meta?.iniUrl || ''}
 * sha256: ${ir.meta?.sha256 || ''}
 * at: ${ir.meta?.generatedAt || ''}
 * profile: ${ir.meta?.profileId || ''}
 * sort_proxies: ${sortProxies}
 */

function main(config) {
    const proxyCount = config?.proxies?.length ?? 0;
    const providerCount =
        typeof config?.['proxy-providers'] === 'object'
            ? Object.keys(config['proxy-providers']).length
            : 0;
    if (proxyCount === 0 && providerCount === 0) {
        throw new Error('配置文件中未找到任何代理');
    }

    const excludeRe = ${bareExclude ? `new RegExp(${JSON.stringify(bareExclude)}, 'i')` : 'null'};
    if (excludeRe && Array.isArray(config.proxies)) {
        config.proxies = config.proxies.filter((p) => !excludeRe.test(p.name));
    }
${sortBlock}
${generalLines}

${dnsBlock}

    config['proxy-groups'] = ${JSON.stringify(groups, null, 4).split('\n').join('\n    ')};
    config['rule-providers'] = ${JSON.stringify(ir.providers, null, 4).split('\n').join('\n    ')};
    config.rules = ${JSON.stringify(ir.rules, null, 4).split('\n').join('\n    ')};

    return config;
}
`;
}
