import yaml from 'js-yaml';

/**
 * @param {object} ir
 * @returns {string}
 */
export function emitStash(ir) {
  const id = ir.meta?.profileId || 'profile';
  const iniUrl = ir.meta?.iniUrl || '';
  const stash = ir.stashMeta || {};
  const name =
    stash.name ||
    (stash.name_template || 'ACL4SSR · {id}').replace(/\{id\}/g, id).replace(/\{ini_url\}/g, iniUrl);
  const desc =
    stash.desc ||
    (stash.desc_template || 'Auto-generated from {ini_url}')
      .replace(/\{id\}/g, id)
      .replace(/\{ini_url\}/g, iniUrl);

  const sortNote = ir.sortProxies
    ? `# Nodes: Stash keeps subscription order inside groups (override cannot re-sort proxies). Use Sub-Store to sort by name, or Network Settings → sort by latency.`
    : `# sort_proxies disabled`;

  const header = [
    `name: ${yamlScalar(name)}`,
    `desc: ${yamlScalar(desc)}`,
    '',
    `# Generated by acl4ssr-override`,
    `# upstream: ${iniUrl}`,
    `# sha256: ${ir.meta?.sha256 || ''}`,
    `# at: ${ir.meta?.generatedAt || ''}`,
    `# Stash arrays default to prepend; #!replace overwrites like overwrite_original_rules=true.`,
    sortNote,
    '',
  ].join('\n');

  const parts = [header];

  if (ir.dns && typeof ir.dns === 'object') {
    const dnsReplaceFields = [
      'fake-ip-filter',
      'default-nameserver',
      'nameserver',
      'proxy-server-nameserver',
      'fallback',
      'fallback-filter',
      'nameserver-policy',
    ];
    let dnsYaml = yaml.dump({ dns: ir.dns }, { lineWidth: 120, noCompatMode: true });
    for (const field of dnsReplaceFields) {
      dnsYaml = dnsYaml.replace(new RegExp(`^(\\s+${field}):`, 'm'), `$1: #!replace`);
    }
    parts.push(dnsYaml.trimEnd(), '');
  }

  if (ir.hosts && typeof ir.hosts === 'object') {
    let hostsYaml = yaml.dump({ hosts: ir.hosts }, { noCompatMode: true });
    hostsYaml = hostsYaml.replace(/^(hosts):/, '$1: #!replace');
    parts.push(hostsYaml.trimEnd(), '');
  }

  const groups = ir.groups.map((g) => {
    const out = { name: g.name, type: g.type };
    if (g.proxies) out.proxies = g.proxies;
    if (g['include-all']) out['include-all'] = true;
    if (g.filter) out.filter = g.filter;
    if (g.url) out.url = g.url;
    if (g.interval != null) out.interval = g.interval;
    if (g.tolerance != null) out.tolerance = g.tolerance;
    return out;
  });

  let groupsYaml = yaml.dump({ 'proxy-groups': groups }, { lineWidth: 200, noCompatMode: true });
  groupsYaml = groupsYaml.replace(/^(proxy-groups):/, '$1: #!replace');
  parts.push(groupsYaml.trimEnd(), '');

  let providersYaml = yaml.dump(
    { 'rule-providers': ir.providers },
    { lineWidth: 200, noCompatMode: true }
  );
  providersYaml = providersYaml.replace(/^(rule-providers):/, '$1: #!replace');
  parts.push(providersYaml.trimEnd(), '');

  let rulesYaml = yaml.dump({ rules: ir.rules }, { lineWidth: 200, noCompatMode: true });
  rulesYaml = rulesYaml.replace(/^(rules):/, '$1: #!replace');
  parts.push(rulesYaml.trimEnd(), '');

  return parts.join('\n') + '\n';
}

function yamlScalar(s) {
  if (s == null) return '""';
  // force quote if special
  if (/[:#{}[\],&*?|>!%@`]/.test(s) || s !== s.trim()) {
    return JSON.stringify(s);
  }
  return s;
}
